# gokaygurcan/dockerfile-ab

language: bash
services: docker

sudo: false

git:
  depth: 1

before_script:
  - docker version
  - docker info

script:
  - docker build --rm -t gokaygurcan/ab:test .
  - docker run --rm gokaygurcan/ab:test -n 1 https://github.com/

notifications:
  email: false
